# Generated by Django 5.0.6 on 2024-06-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_quantity_cartitem_product_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shipping_address',
            field=models.TextField(max_length=255),
        ),
    ]
